const data = {
    products: [
        {
            _id: '1',
            name: 'Hair Dryer',
            category: 'Fashion',
            image: '/images/1.jpg',
            price: 120,
            countInStock:16,
            brand: 'NV',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Speaker',
            category: 'Tech',
            image: '/images/2.jpg',
            price: 150,
            countInStock:30,
            brand: 'Kisonli',
            rating: 3.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Charger',
            category: 'Tech',
            image: '/images/3.jpg',
            price: 80,
            countInStock:5,
            brand: 'Samsung',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Hammock',
            category: 'Entertainment',
            image: '/images/4.jpg',
            price: 90,
            countInStock:10,
            brand: 'N/A',
            rating: 3.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Massager',
            category: 'Health',
            image: '/images/5.jpg',
            price: 100,
            countInStock:15,
            brand: 'Mimo',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Dust Cleaner',
            category: 'Households',
            image: '/images/6.jpg',
            price: 20,
            countInStock:20,
            brand: 'N/A',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
    ],
};
export default data;